CREATE TABLE "bf_v9"."role_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bf_v9"."role_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"requested_role" text NOT NULL,
	"reason" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_by" text,
	"reviewed_at" timestamp with time zone,
	"review_note" text
);
--> statement-breakpoint
ALTER TABLE "bf_v9"."user" ADD COLUMN "roles" text[] DEFAULT '{"customer"}' NOT NULL;--> statement-breakpoint
ALTER TABLE "bf_v9"."role_requests" ADD CONSTRAINT "role_requests_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "bf_v9"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bf_v9"."role_requests" ADD CONSTRAINT "role_requests_reviewed_by_user_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "bf_v9"."user"("id") ON DELETE no action ON UPDATE no action;